# Generated by Django 2.2.4 on 2020-03-30 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='courses/imagens', verbose_name='Imagem'),
        ),
    ]
