# Generated by Django 2.2.4 on 2020-04-15 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_announcement_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='announcements', to='courses.Course', verbose_name='Curso'),
        ),
    ]
