# Generated by Django 2.2.4 on 2020-05-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_lesson_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.TextField(default=0, verbose_name='Valor do curso'),
        ),
    ]
