# Generated by Django 2.2.4 on 2020-05-10 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(max_length=50, verbose_name='Valor do curso'),
        ),
    ]
